### ISSUE TITLE
Add Today Overview Tab 

### ISSUE THREAD

**Issue by VadoseCrane0** [pbobyn91/weekly_meal_planner#12]
We should add a tab for an overview of all events going on for that day eg:
- what meals are planned for the day
- chores planned for the day
- ingredients that you may need to pick up
- fitness goals 
etc... 

This should become the landing page for when a user uses the app they can clearly see what is planned throughout the day

**Comment by pbobyn91** [comment]
I think this makes sense to add. I agree with this page.
