### ISSUE TITLE
Add a Breakfast tab

### ISSUE THREAD

**Issue by pbobyn91** [pbobyn91/weekly_meal_planner#2]
Add a breakfast tab similar to the Dinner tab

**Comment by VadoseCrane0** [comment]
I think breakfast, lunch and dinner should be under one "meals" tab.
similar to what they do here
![image](https://user-images.githubusercontent.com/59963296/161442041-dde52ca6-2232-4e3b-8a3a-71f532306001.png)

maybe with some sort of google calendar element that will allow you to choose which day you want to add/edit meals for

**Comment by pbobyn91** [comment]
I am not sure if I agree with that. Although no matter which way we go we could still keep the tasks so we can add them in separately. We will need to update the backend with these tasks anyways
